spring:
  application:
    name: multi-module
  profiles:
    active: local
  config:
    import:
      - logging.yaml
      - db-main.yaml
---
spring:
  config:
    activate:
      on-profile: local

---
spring:
  config:
    activate:
      on-profile: local-dev
---
spring:
  config:
    activate:
      on-profile: dev

---
spring:
  config:
    activate:
      on-profile: staging

---
spring:
  config:
    activate:
      on-profile: live
